### ISSUE TITLE
Redundant commented code should be removed

### ISSUE THREAD

**Issue by birtony** [izhuravlev/z-Note#5]
It has come to my attention that there is a number of commented out lines of code in [index.html](https://github.com/izhuravlev/z-Note/blob/9674128ba6f4d2bd2d73b50e8ae021331a556d19/index.html):
https://github.com/izhuravlev/z-Note/blob/9674128ba6f4d2bd2d73b50e8ae021331a556d19/index.html#L82-L89

I suggest that these lines should be removed as redundant.

**Comment by izhuravlev** [comment]
Sure, @birtony, go ahead - I did not have enough time to delete those.
